### ISSUE TITLE
[deps] Update peerdeps for commander

### ISSUE THREAD

**Issue by smolinari** [withfig/autocomplete-tools#90]
Hi,

Your package is causing peer dependency errors because it is 3 major versions behind Commander. Can you please update the peer deps?

https://github.com/withfig/autocomplete-tools/blob/49bd0070acfb65aae84393aa544b9b32247f99db/integrations/commander/package.json#L35

Thanks!

Scott

**Comment by ruscon** [comment]
@grant0417 @fedeci ping

**Comment by grant0417** [comment]
This is updated, will try to keep this updated more in the future, sorry for the delay on this!

**Comment by devm33** [comment]
👋 This is behind again 14 vs 11

https://github.com/withfig/autocomplete-tools/blob/104377c19a91ca8a312cb38c115a74468f6227cb/integrations/commander/package.json#L35

https://www.npmjs.com/package/commander

Perhaps the peerDependencies semver range could be loosened so it's not an issue? e.g. `>=11.1.0` instead of `^11.1.0`

PR: https://github.com/withfig/autocomplete-tools/pull/406
